name: server
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.4.0
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  mailer: ^7.1.0
  postgres: ^3.5.9
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
